"""rename department

Revision ID: 2ecdea868257
Revises: 6bb890fb7fdd
Create Date: 2024-04-04 09:32:31.272949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecdea868257'
down_revision = '6bb890fb7fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')    
    # ### end Alembic commands ###
